
.PHONY: start

DOCKER_COMPOSE_YAML = docker-compose-mysql-python.yaml

start:
	docker-compose -f ${DOCKER_COMPOSE_YAML} pull
	docker-compose -f ${DOCKER_COMPOSE_YAML} up -d

stop:
	docker-compose -f ${DOCKER_COMPOSE_YAML} down

status:
	docker-compose -f ${DOCKER_COMPOSE_YAML} ps

enter-python:
	docker exec -it python-latest /bin/bash

