apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/josef/data/minikube/kafka-pv1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/josef/data/minikube/prometheus-pv1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/josef/data/minikube/postgresql-pv1
